package com.ptoye.TestFormBug;

public final class TestFormBug extends javax.swing.JFrame {

  static final String titleString = "Title";


  /**
   * Creates new form TestKiller
   */
  public   TestFormBug() {
      initComponents();
      }

    /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle(TestFormBug.titleString);
    setLocationByPlatform(true);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables


}
